import Head from "next/head";

const SEO = ({ pageTitle }) => (
  <>
    <Head>
      <title> {pageTitle && `${pageTitle} - FAMZ `}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by MDQ-Developers" />
      <meta name="robots" content="noindex, follow" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" href="/favicon.png" />
      {/* <!-- Google tag (gtag.js) --> */}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DZFK0X5VW8"></script>
{/* <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)}
  gtag('js', new Date());

  gtag('config', 'G-DZFK0X5VW8');
</script> */}
    </Head>
  </>
);
 
export default SEO;
